name: Test and Coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  codecoverage:
    runs-on: ubuntu-latest
    container: golang:1.21

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v1
        with:
          go-version: '1.21'

      - name: Run tests and coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}